name: Add issues to project

on:
  issues:
    types: [opened, transferred]

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue to @SteffenGottschalk/projects/1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/SteffenGottschalk/projects/1
          github-token: ${{ secrets.PROJECT_TOKEN }}
